# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    credit_card_validator:
        class: AppBundle\Service\CreditCardValidator

    train_information:
        class: AppBundle\Service\TrainInformation

    train_manager:
        class: AppBundle\Service\TrainManager
        arguments: [@doctrine.odm.mongodb.document_manager, @train_information]
